### ISSUE TITLE
Auto Install Pagodabox não está rolando.

### ISSUE THREAD

**Issue by fhferreira** [laraerp/laraerp#1]
Aparentemente há problemas com a utilização do sqLite.

**Comment by jansenfelipe** [comment]
Opa! Obrigado pelo report @fhferreira ! Tinha um erro no boxfile, e aparentemente está resolvido.

**Comment by fhferreira** [comment]
vlw mAN

**Comment by fhferreira** [comment]
Fiz o teste e a instalação rolou de boa, só está dando uns problemas de 404 e de banco em algumas telas

**Comment by jansenfelipe** [comment]
Pois é! Na verdade esse projeto eu apenas comecei ... E uma das minhas metas que determinei no reveillon era fechar a primeira versão rs .. Só que estou numa correria...

**Comment by fhferreira** [comment]
Imagino, é um projeto bacana, só reportei pq vi o projeto no pagodabox e fui testar rsrs. 
também to na correria aqui. rsrs
