### ISSUE TITLE
O projeto morreu?

### ISSUE THREAD

**Issue by marabesi** [laraerp/laraerp#10]
Faz mais de um ano do último commit, está tendo suporte ainda?

**Comment by jansenfelipe** [comment]
@marabesi não consegui evoluir com o projeto por falta de tempo :/

**Comment by marcelaodev** [comment]
@jansenfelipe tem interesse futuro?

Estou analisando usar esse projeto como base pra API de um sistema

**Comment by jansenfelipe** [comment]
@marcelobcortes tenho interesse! Percebo que é um projeto promissor. Existe demanda por soluções opensource assim.

**Comment by marabesi** [comment]
Bacana, vou analisa (não prometo) mas vou tentar contribuir com algo.

Abs!

**Comment by marcelobcortes** [comment]
f

**Comment by marcelaodev** [comment]
@jansenfelipe podemos conversar via algum chat?
gostaria de compreender melhor seu projeto, onde queria chegar, qual foco, etc
estou realmente interessado em contribuir na parte backend (Blade não me interessa)
