### ISSUE TITLE
Site off

### ISSUE THREAD

**Issue by tghelere** [laraerp/laraerp#11]
Bom dia, o site http://laraerp.org/ está fora do ar.

**Comment by marcosrocha85** [comment]
Infelizmente acredito que o projeto foi abandonado. Uma pena, pois era justamente o que eu estou precisando.

**Comment by tghelere** [comment]
Também acho, uma pena. Se eu tivesse tempo e conhecimento necessário tentaria dar continuidade nesse projeto. 
Mas estava pensando aqui agora, pode haver uma esperança. Dê uma verificada nos repositórios de quem fez fork desse projeto, vai que alguém deu continuidade :smiley: 
https://github.com/laraerp/laraerp/network/members

**Comment by dfares1987** [comment]
pelo jeito ninguem achou nda

**Comment by marcosrocha85** [comment]
Vamo ve se eu consigo. Fiquem ligados.

**Comment by HamirDhanquer** [comment]
A gente poderia voltar a tocar esse projeto.

**Comment by marcosrocha85** [comment]
Estou montando um container do Docker para poder rodar e atualizar o projeto. Quanto ao site, vamos ter que mudar o domínio, pois laraerp.org está em posse de um daqueles hosts que compram pra revender.

**Comment by marcosrocha85** [comment]
Amigos, hospedei temporariamente no meu servidor até que eu consiga resolver a questão do domínio: https://laraerp.tinkertecnologia.com e o login e senha são os mesmos.

**Comment by marcosrocha85** [comment]
OK, estou desativando o https://laraerp.tinkertecnologia.com, pois na atual situação não tenho condições de registrar e manter um domínio para o LaraERP. 😥

**Comment by tghelere** [comment]
E ai @marcosrocha85 , como vai?
Eu te entendo, até pq este projeto pelo jeito morreu, pelo menos nesse repositório inicial, talvez algum fork pode ter dado continuidade, é uma pena. Muito obrigado de qualquer forma.
abraço
