### ISSUE TITLE
A que pé está o projeto?

### ISSUE THREAD

**Issue by emtudo** [laraerp/laraerp#3]
@jansenfelipe a que pé está este projeto?

Estou desenvolvendo um na empresa que trabalho, talvez consigo liberação para trabalhar neste dependendo o pé que está, porém estava vendo alguns seeds,
não entendi algo:

Porque o fator de kilo não é tratado da mesma forma do litro?

 //Massa
        $kg = UnidadeMedidaFator::create(['unidade_medida_id' => $massa->id, 'simbolo' => 'Kg', 'fator' => 1000]);
        $g = UnidadeMedidaFator::create(['unidade_medida_id' => $massa->id, 'simbolo' => 'g', 'fator' => 1]);
        //Volume
        $L = UnidadeMedidaFator::create(['unidade_medida_id' => $volume->id, 'simbolo' => 'L', 'fator' => 1]);
        $ml = UnidadeMedidaFator::create(['unidade_medida_id' => $volume->id, 'simbolo' => 'ml', 'fator' => 0.001]);

**Comment by jansenfelipe** [comment]
@emtudo tá engatinhado rsrs.. Faz uns meses que nem encosto no projeto.. Mas gostaria muito de avançar com ele!

Sobre os fatores das unidade kilo e litro:

Quilograma = 10^3
Litro = 10^0

Veja os múltiplos e submúltiplos de cada um:

https://pt.wikipedia.org/wiki/Litro#M.C3.BAltiplos_e_subm.C3.BAltiplos
https://pt.wikipedia.org/wiki/Quilograma#M.C3.BAltiplos_e_subm.C3.BAltiplos

**Comment by emtudo** [comment]
boa! vou ver mais sobre isso!

vamos continuar conversando!
